### ISSUE TITLE
Space settings to allow voting with alias

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3852] opened 2023-04-30 19:02 UTC

**Comment by samuveth** [comment] 2023-05-02 06:30
Hey there @aurelianoB! I noticed this item was moved to the "Todo" list without any description.

**Comment by bonustrack** [comment] 2023-05-08 08:47
There is already an space parameter to allow voting with alias, the missing parts are:
- Have a way on space settings to enable voting / propose with alias
- Make default voting and propose works with alias if a space has the parameter enabled

**Comment by samuveth** [comment] 2023-10-16 02:06
Duplicate of https://github.com/snapshot-labs/snapshot/issues/2844

**Closed by samuveth** 2023-10-16 02:06 UTC
Labels: enhancement
