### ISSUE TITLE
Snapshot default theme should be light not dark

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#4486] opened 2024-01-08 13:57 UTC

**Comment by wa0x6e** [comment] 2024-01-08 14:15
Why not default to system theme ?

**Comment by samuveth** [comment] 2024-01-08 14:15
Duplicate of https://github.com/snapshot-labs/snapshot/issues/4486

**Comment by samuveth** [comment] 2024-01-08 14:16
I meant #4480

**Closed by samuveth** 2024-01-08 14:15 UTC
