### ISSUE TITLE
Can't join some spaces

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1048] opened 2021-11-14 06:32 UTC
**Describe the bug**
Many users report that they can't join few spaces (even after clearing the cache) But I can't reproduce this issue

- Need steps to reproduce

**Comment by beepidibop** [comment] 2021-11-14 07:07
I think I have isolated it to spaces that require you to agree to terms of service before you are able to join/vote. 
![image](https://user-images.githubusercontent.com/63800471/141670963-1d9caa6c-4943-4d22-a33c-8a35e17faa1a.png)
I am able to join spaces that don't require such confirmation. However, when I try to join sushi and dydx, the join button will circle around, then return back to "Join" without joining the space.

Steps to reproduce:
1. Clear cache, reconnect wallet (Metamask or Frame)
2. Click join on a random space that doesn't have terms of agreements
3. Sign message for alias
4. Successfully join said random space in step 2
5. Click join on Sushi
6. Click agree to the terms of service
7. Join button turns to the circling animation for a few seconds
8. Button reverts back to join, Sushi not joined


I also tried skipping over joining a random space. In that case, it'll ask the wallet to sign for an alias, but the spinning animation still reverts to a "Join" button without joining the space.

**Comment by beepidibop** [comment] 2021-11-14 21:52
I tested it a bit more. I can join sushi with an EoA that doesn't have ENS lookup set. But couldn't with one that has ENS lookup set.

**Comment by ChaituVR** [comment] 2021-11-16 15:53
@beepidibop can you try this on incognito (allow only metamask in incognito)

**Comment by beepidibop** [comment] 2021-11-16 23:20
Tried in chrome incognito with only the MetaMask extension in one run, with only the Frame extension in another. Still couldn't join.

**Comment by ChaituVR** [comment] 2021-11-17 02:53
@beepidibop can you also try disabling frame too, because i have seen few issues on someother website with frame extension, maybe this could be related (i have tried installing frame but cant reproduce)

**Comment by beepidibop** [comment] 2021-11-17 04:04
Yeah, I tried it with MetaMask as the only extension enabled (and incognito) and it still doesn't work.

**Comment by samuveth** [comment] 2021-12-02 04:47
> Yeah, I tried it with MetaMask as the only extension enabled (and incognito) and it still doesn't work.

Just tested it with Chrome in Incognito mode on a Mac and it works.

**Comment by justwanttoknowathing-github** [comment] 2022-02-04 23:51
I suspect this is the same as #640 but that the culprit condition is a combination of all the gotchas brought up in both issues:

- Using a ledger hardware wallet
- Using an EOA with an ENS address + reverse lookup
- Trying to join one of the spaces that requires a terms agreement

If any one of those conditions are not true, I can successfully join the space, but if all three are true I cannot, even from an incognito window with the only enabled extension being Metamask.

Reproduces in all of:
- Linux: Chrome Stable 98.0.4758.80 + Metamask 10.8.1
- Linux: Firefox Stable 96.0/20220106144528 + Metamask 10.8.1
- Linux: Chrome Dev 100.0.4867.0 + Metamask 10.9.0
- Windows: Chrome Stable 98.0.4758.82 + Metamask 10.9.0

**Comment by justwanttoknowathing-github** [comment] 2022-03-30 22:51
Had some time to dig into this a little more; some of my last comment was wrong: I think the terms agreement doesn't matter and that the culprit may just be ENS (+ reverse lookup?) and ledger.

I got this reproducing in a local snapshot instance and removing the code that calls the terms agreement doesn't allow me to join spaces with a failing wallet.

I'm not the greatest at javascript, nor remotely familiar with the snapshot code, but I noticed a little crumb that may point towards the issue: the resulting IPFS entries differ significantly between a failing and succeeding wallet. Though both sign requests like:

`{"address":"0xaddress","sig":"0xlongsig","data":{"domain":{"name":"snapshot","version":"0.1.4"},"types":{"Follow":[{"name":"from","type":"address"},{"name":"space","type":"string"}]},"message":{"from":"0xotheraddress","space":"curve.eth","timestamp":1648679434}}}`

the failing wallet's resulting data stored in IPFS instead looks like:

`{"address":"0xaddress","msg":"0xlongmsg","sig":"0xlongsig","version":"2"}`

whereas the succeeding wallet's data looks more like what was signed.

Maybe that's helpful to someone more familiar with what's going on -- or maybe that's just what happens when the signature isn't valid and this is all a deeper ethers.js issue. :)

If anyone has any suggestions for debugging this, now that I've got it happening in a dev environment, I'm all ears.

**Comment by samuveth** [comment] 2022-05-17 08:15
@ChaituVR @metrox-eth is this an issue that is still being reported?

**Comment by justwanttoknowathing-github** [comment] 2022-05-18 19:09
> @ChaituVR @metrox-eth is this an issue that is still being reported?

This still happens for me both in prod (snapshot.org) snapshot and an up-to-date local version running the 'develop' branch.

**Comment by justwanttoknowathing-github** [comment] 2022-07-14 21:24
This is now fixed for me with the version of snapshot running in prod. I hadn't retested with the develop branch since May 18, so not sure what did it, but it's convenient that it's working now.

Thanks Snapshot folks.

**Comment by samuveth** [comment] 2022-07-16 04:41
Awesome, it looks like it was related to a query limit we had. Thanks for letting us know!

**Closed by samuveth** 2022-07-16 04:41 UTC
Labels: help wanted, need reproduce
