### ISSUE TITLE
Uploading a space image take too long to appear

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1279] opened 2021-12-16 10:38 UTC
When I add a space image, it take around 5mn for the image to finally appear, this is quite confusing. Something is wrong with either the worker that does image resize or gateway that take too long to resolve the uploaded image.

**Comment by bigint** [comment] 2021-12-16 11:47
@bonustrack I think you might have checked in downtime, I can't reproduce this too as show in https://github.com/snapshot-labs/snapshot/issues/1278#issuecomment-995718080

**Closed** 2022-06-14 07:44 UTC
Labels: bug-report, wontfix
