### ISSUE TITLE
[BUG] - Unable to sign message on mobile using TrustWallet, DeFi Wallet and potentially others

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#3174] opened 2022-09-23 10:39 UTC
### Briefly describe the bug.

These wallets can't cast a vote through Wallet Connect on mobile

### How can we reproduce the bug?

I am unable to vote on mobile with TrustWallet and DeFi Wallet through Wallet Connect, Metamask  is working fine tho.

Strange thing when I wire my iPhone to my mac to get the devtools, TrustWallet works but DeFi Wallet don't, throwing wrong signature error.
I have made screenshot for each wallets, but I am not too sure how to provide the context for this issue as it's seems that the behavior change when the device is connected to a mac.

### What is the expected behaviour?

I should be able to use Trust Wallet, DeFi Wallet, Game Stop Wallet, and so on to cast a vote on Snapshot from mobile.

### Can you attach screenshots?

Failed attempt to cast a vote using Trust Wallet and DeFi Wallet on an iPhone
Console on the mac
<img width="999" alt="Capture d’écran 2022-09-23 à 17 12 52" src="https://user-images.githubusercontent.com/55286013/191942979-d305b1d2-8e55-492c-ad6d-495a3a5f82bc.png">
UI on the iPhone
![IMG_7590](https://user-images.githubusercontent.com/55286013/191942357-7b582cad-fd36-4c5b-801d-7b0e25712fdf.PNG)

Strangely it works with Trust Wallet when the iPhone is wired in USB to the mac to get the developers tools / console
<img width="999" alt="Capture d’écran 2022-09-23 à 17 11 00" src="https://user-images.githubusercontent.com/55286013/191943073-69db8a6d-af32-4e36-8d5e-1301e4cedd37.png">

### Can you provide your device specific details below?

1. Device Type - [Mobile]
2. Device OS - [iOS]
3. OS Version - [Latests]
4. Browser - [Safari]
5. Browser Version - [Latest]
6. Wallet - [Trust Wallet, DeFi Wallet, GameStop Wallet]
7. Space - [Any]

**Comment by IlyaLoshchinin** [comment] 2022-10-12 16:52
Hello. I'm getting the same error too with Argent app.

**Comment by bonustrack** [comment] 2022-10-12 17:30
@IlyaLoshchinin Do you use the iOS or Android app? And is it updated to latest version of Argent?

**Comment by IlyaLoshchinin** [comment] 2022-10-12 20:26
I use Android 13, and up to date the Argent app. Thank you.

**Comment by samuveth** [comment] 2022-10-13 08:40
I can't reproduce the issue with Argent connected through WalletConnect.

Argent version 4.8.2.84
Android Android 12

**Comment by samuveth** [comment] 2022-10-22 14:14
Also can't reproduce with TrustWallet connected through WalletConnect.

TrustWallet version 6.53
Android version 12

**Comment by n4n0GH** [comment] 2022-10-24 16:50
Can reproduce this with my codebase: https://github.com/alchemix-finance/alchemix-v2-frontend/blob/fix/snapshot/src/middleware/snapshot.js

I can't seem to get proper signatures going on and instead receive a "wrong signature" error as a result.

Using Metamask and Chrome on MacOS; haven't tested with other browser or OS combinations.

@samuveth

**Comment by samuveth** [comment] 2022-10-24 16:55
@n4n0GH can you share a link to your integration ui and the proposal id where I can test this?

**Comment by n4n0GH** [comment] 2022-10-24 17:20
@samuveth https://alchemix-v2-frontend-jk61b9k9u-alchemix.vercel.app/

You need to connect a wallet and then click on "Governance" to see the proposal.

**Comment by n4n0GH** [comment] 2022-10-25 11:26
fixed in my case; I was passing the address as a string to the vote function instead of a checksum of the address

**Closed** 2022-11-30 17:18 UTC
Labels: bug-report, need reproduce
