### ISSUE TITLE
Changing Space before loading proposals showing incorrect data

### ISSUE THREAD

**Issue by sasicodes** [snapshot-labs/snapshot#1288] opened 2021-12-17 14:00 UTC
Rapidly changing spaces before it loads proposals shows previous space proposals.

1. Go to HomePage
2. Click on any space and change to another one before loading proposals
3. We can see the loaded proposals data for previous space is rendered on screen

**Expected behavior**
Should show current space proposals.

**Screenshots**
https://www.loom.com/share/5bba4d90253d4281914ebc50e2c3487f

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave
 - Version  1.33.106

Old API data is loaded into proposals cache.

**Comment by sasicodes** [comment] 2021-12-17 14:02
Maybe we can disable the spaces in sidebar until the proposal loads?

WDYT? @samuveth @bonustrack

**Comment by bigint** [comment] 2021-12-17 14:08
Good catch @sasicodes I can reproduce this 👍🏻

**Comment by bigint** [comment] 2021-12-17 14:09
> Maybe we can disable the spaces in sidebar until the proposal loads?

I think its a bad UX, what if the proposal loads forever because of some issues, you need to hard reload to enable the sidebar again 🙇🏻 

Leaving to maintainers 🤗

**Comment by bigint** [comment] 2021-12-17 14:21
I can see new requests gets merged to already loaded one

<img width="479" alt="image" src="https://user-images.githubusercontent.com/69431456/146557257-80fbbe31-da42-419a-b4e5-b88e678aec94.png">

**Comment by samuveth** [comment] 2021-12-17 14:29
Good catch! I'll work on this

**Closed** 2021-12-20 16:45 UTC
